version: '3.4'

services:
  postgres_ced:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=ced
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - database

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@hamsterapps.net
      - PGADMIN_DEFAULT_PASSWORD=12345
    networks:
      - database

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: 'mariadb'
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_DATABASE=secret
      - MYSQL_PASSWORD=supersecret
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    networks:
      - database
volumes:
  pgdata:
    driver: local
networks:
  database:
    external: true
